import type { ChartDrawTool } from './chart-drawings.js';

export const CHART_DRAWING_TYPE_LABELS: Record<string, string> = {
  line: 'Línea tendencia',
  ray: 'Rayo',
  'ext-line': 'Línea extendida',
  'info-line': 'Línea info',
  'trend-angle': 'Ángulo tendencia',
  regression: 'Regresión',
  hline: 'Línea horizontal',
  hray: 'Rayo horizontal',
  vline: 'Línea vertical',
  rectangle: 'Rectángulo',
  fibonacci: 'Fibonacci',
  'fib-trend-ext': 'Fib. extensión',
  'fib-time-zone': 'Fib. temporal',
  'gann-fan': 'Abanico Gann',
  'gann-grid': 'Cuadrícula Gann',
  'gann-square': 'Cuadrado Gann',
  channel: 'Canal',
  pitchfork: 'Tridente',
  'text-label': 'Texto',
  'brush-stroke': 'Trazo',
  'cross-marker': 'Marca cruz',
  'dot-marker': 'Punto',
  'dot-halo-marker': 'Punto resaltado',
  'arrow-marker': 'Flecha',
  'arrow-circle-marker': 'Flecha en círculo',
};

export const CHART_DRAW_TOOL_LABELS: Record<ChartDrawTool, string> = {
  select: 'Puntero',
  crosshair: 'Regla / medida',
  cross: 'Marca cruz',
  dot: 'Punto',
  'dot-halo': 'Punto resaltado',
  arrow: 'Flecha',
  'arrow-circle': 'Flecha en círculo',
  line: 'Línea tendencia',
  ray: 'Rayo',
  'info-line': 'Línea info',
  'ext-line': 'Línea extendida',
  'trend-angle': 'Ángulo tendencia',
  hline: 'Línea H',
  hray: 'Rayo H',
  vline: 'Línea V',
  regression: 'Regresión',
  channel: 'Canal',
  pitchfork: 'Tridente',
  fibonacci: 'Fibonacci',
  'fib-trend-ext': 'Fib. extensión',
  'fib-time-zone': 'Fib. temporal',
  'gann-fan': 'Abanico Gann',
  'gann-grid': 'Cuadrícula Gann',
  'gann-square': 'Cuadrado Gann',
  rectangle: 'Rectángulo',
  text: 'Texto',
  brush: 'Pincel',
  highlighter: 'Resaltador',
  'arrow-up': 'Marcador arriba',
  'arrow-down': 'Marcador abajo',
};
