import type { InstrumentSearchResult } from './types.js';

/** IBEX 35 — símbolos Yahoo (.MC = Bolsa de Madrid) */
export const IBEX35_INSTRUMENTS: InstrumentSearchResult[] = [
  { symbol: 'SAN', yahooSymbol: 'SAN.MC', name: 'Banco Santander', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'BBVA', yahooSymbol: 'BBVA.MC', name: 'BBVA', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'IBE', yahooSymbol: 'IBE.MC', name: 'Iberdrola', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ITX', yahooSymbol: 'ITX.MC', name: 'Inditex', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'TEF', yahooSymbol: 'TEF.MC', name: 'Telefónica', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'REP', yahooSymbol: 'REP.MC', name: 'Repsol', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'FER', yahooSymbol: 'FER.MC', name: 'Ferrovial', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ACS', yahooSymbol: 'ACS.MC', name: 'ACS', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ENG', yahooSymbol: 'ENG.MC', name: 'Enagás', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'GRF', yahooSymbol: 'GRF.MC', name: 'Grifols', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'AENA', yahooSymbol: 'AENA.MC', name: 'Aena', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'IAG', yahooSymbol: 'IAG.MC', name: 'IAG', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'MAP', yahooSymbol: 'MAP.MC', name: 'Mapfre', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'MEL', yahooSymbol: 'MEL.MC', name: 'Meliá Hotels', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'RED', yahooSymbol: 'RED.MC', name: 'Redeia', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'CLNX', yahooSymbol: 'CLNX.MC', name: 'Cellnex', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'AMS', yahooSymbol: 'AMS.MC', name: 'Amadeus', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'CABK', yahooSymbol: 'CABK.MC', name: 'CaixaBank', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'SAB', yahooSymbol: 'SAB.MC', name: 'Banco Sabadell', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'LOG', yahooSymbol: 'LOG.MC', name: 'Logista', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'COL', yahooSymbol: 'COL.MC', name: 'Inmobiliaria Colonial', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'NTGY', yahooSymbol: 'NTGY.MC', name: 'Naturgy', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ACX', yahooSymbol: 'ACX.MC', name: 'Acerinox', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'FDR', yahooSymbol: 'FDR.MC', name: 'Fluidra', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'VIS', yahooSymbol: 'VIS.MC', name: 'Viscofan', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ROVI', yahooSymbol: 'ROVI.MC', name: 'Laboratorios Rovi', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'PHM', yahooSymbol: 'PHM.MC', name: 'PharmaMar', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ALM', yahooSymbol: 'ALM.MC', name: 'Almirall', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'UNI', yahooSymbol: 'UNI.MC', name: 'Unicaja Banco', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'BKT', yahooSymbol: 'BKT.MC', name: 'Bankinter', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'SCYR', yahooSymbol: 'SCYR.MC', name: 'Sacyr', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'IDR', yahooSymbol: 'IDR.MC', name: 'Indra', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'CAF', yahooSymbol: 'CAF.MC', name: 'CAF', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ELE', yahooSymbol: 'ELE.MC', name: 'Endesa', exchange: 'BME', currency: 'EUR', type: 'stock' },
  { symbol: 'ANA', yahooSymbol: 'ANA.MC', name: 'Acciona', exchange: 'BME', currency: 'EUR', type: 'stock' },
];
